remote_theme: "mmistakes/minimal-mistakes@4.28.0"

locale: "en-US"
title: "Chintha Tellambura"
title_separator: "-"
name: "Chintha Tellambura"
description: "Research and academic website"

url: "https://chinthatellambura.github.io"
baseurl: "/chinthatellambura.github.io-website"
repository: "chinthatellambura/chinthatellambura.github.io-website"

minimal_mistakes_skin: "default"

search: true
search_provider: lunr

author:
  name: "Chintha Tellambura"
  avatar: "/assets/images/chintha.jpg"
  bio: "Ph.D., P.Eng., Professor, IEEE Fellow"
  #location: ""
  #email: "ct4@ualberta.ca"
  links:
    - label: "University of Alberta"
      icon: "fas fa-fw fa-university"
      url: "https://apps.ualberta.ca/directory/person/ct4"

    - label: "Dep. of Electrical and Computer"
      icon: "fas fa-fw fa-university"
      url: "https://www.ualberta.ca/en/engineering/electrical-computer-engineering/index.html"
      
    - label: "ct4@ualberta.ca"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:ct4@ualberta.ca"
      
    - label: "+1 780 492 7228"
      icon: "fas fa-fw fa-phone"
      url: "tel:+1 780 492 7228"
      
    - label: "Office: ICE 11-340"
      icon: "fas fa-fw fa-building"
      url: "Office: ICE 11-340"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/chintha-tellambura-ba841920/"

    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=7hw2Ha4AAAAJ&hl=en"

    - label: "ResearchGate"
      icon: "fab fa-fw fa-researchgate"
      url: "https://www.researchgate.net/profile/Chintha-Tellambura"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chinthatellambura"

include:
  - _pages

exclude:
  - docs
  - test
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - CHANGELOG.md
  - README.md
  - LICENSE
  - tmp
  - log
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - .asset-cache

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

permalink: /:categories/:title/

paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
