remote_theme: "mmistakes/minimal-mistakes@4.28.0"

locale: "en-US"
title: "Chintha Tellambura"
title_separator: "-"
name: "Chintha Tellambura"
description: "Research and academic website"

url: "https://chinthatellambura.github.io"
baseurl: "/chinthatellambura.github.io-website"
repository: "chinthatellambura/chinthatellambura.github.io-website"

minimal_mistakes_skin: "default"

search: true
search_provider: lunr

author:
  name: "Chintha Tellambura"
  avatar: "/assets/images/chintha.jpg"
  bio: "Ph.D., P.Eng., Professor, IEEE Fellow"
  #location: ""
  email: "ct4@ualberta.ca"
  links:
    - label: "+1 780 492 7228"
      icon: "fa-duotone fa-thin fa-circle-phone"
      #url: "https://github.com/chinthatellambura"

    - label: "Office: ICE 11-340"
      icon: "fa-duotone fa-thin fa-building"
      #url: "https://github.com/chinthatellambura"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/chinthatellambura"

include:
  - _pages

exclude:
  - docs
  - test
  - vendor
  - node_modules
  - Gemfile
  - Gemfile.lock
  - CHANGELOG.md
  - README.md
  - LICENSE
  - tmp
  - log
  - .sass-cache
  - .jekyll-cache
  - .bundle
  - .asset-cache

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

permalink: /:categories/:title/

paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true

  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
